### PR TITLE
Converted Ansible Playbook to Role

### PR DESCRIPTION
**Pull request by rbicelli**
Hello!
I converted the ansible playbook to an ansible role.
Thanks for the template, very useful!

### CODE REVIEW

**Comment by v-zhuravlev** [comment]
Hi @rbicelli , would it better to put `<role>/files` to .gitignore list so we don't track two copies of same files?

**Comment by rbicelli** [comment]
Of course! I forgot to add it!
Would you provide it?

**Comment by v-zhuravlev** [comment]
I think It would be great  if you can just update your PR by adding commit with .gitignore update.

**Comment by rbicelli** [comment]
Ok committed with modifications.

**Comment by v-zhuravlev** [comment]
Thanks!

**Pull request merged**
